name = "GeneticAlgorithm"
uuid = "1d728517-7ff6-4cc0-a11d-05e2c12d719c"
authors = ["Max Hiort <m.hiort@campus.tu-berlin.de>", "Konstantin Prieb <k.prieb@campus.tu-berlin.de>", "Fenja Schulz <f.schulz@campus.tu-berlin.de>", "Kirill Simonov <k.simonov@campus.tu-berlin.de>"]
version = "1.0.0-DEV"

[deps]
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"

[compat]
julia = "1.10"
